# Generated by Django 5.0.4 on 2024-04-15 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_author_productlike_product_like_users'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='like_users',
        ),
        migrations.RemoveField(
            model_name='product',
            name='author',
        ),
        migrations.DeleteModel(
            name='ProductLike',
        ),
    ]
