# Generated by Django 5.0.4 on 2024-04-18 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_hashtag_product_hashtags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hashtags',
        ),
        migrations.DeleteModel(
            name='Hashtag',
        ),
    ]
