# Generated by Django 5.0.4 on 2024-04-19 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_hashtags_delete_hashtag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hashtag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.TextField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='hashtag',
            field=models.ManyToManyField(blank=True, related_name='hashtag', to='products.hashtag'),
        ),
    ]
